version: '3'

services:
  db:
    image: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./TACO.sql:/docker-entrypoint-initdb.d/TACO.sql
      - postgres_data:/data/db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: TACO
      POSTGRES_PASSWORD: "vila@02100260"
    restart: unless-stopped

  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
    - ./:/app
    depends_on:
      - db

volumes:
  postgres_data:
