# Generated by Django 4.2 on 2023-04-07 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Calories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alimento', models.CharField(max_length=255)),
                ('cal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('p', models.DecimalField(decimal_places=2, max_digits=10)),
                ('c', models.DecimalField(decimal_places=2, max_digits=10)),
                ('g', models.DecimalField(decimal_places=2, max_digits=10)),
                ('f', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
